version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.36.0
  - dependency-name: eslint
    versions:
    - 7.24.0
  - dependency-name: karma-webpack
    versions:
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
    - 5.0.0
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.1
    - 7.13.10
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.15
    - 7.13.5
    - 7.13.8
    - 7.13.9
  - dependency-name: karma
    versions:
    - 6.0.3
    - 6.0.4
    - 6.1.0
    - 6.1.1
    - 6.1.2
    - 6.2.0
    - 6.3.0
    - 6.3.1
  - dependency-name: jasmine-core
    versions:
    - 3.7.0
    - 3.7.1
  - dependency-name: jasmine
    versions:
    - 3.7.0
  - dependency-name: "@datastructures-js/priority-queue"
    versions:
    - 5.0.2
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
    - 7.1.0
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
